[#25] feat(Tag): 태그를 이용하여 게시물 검색하는 기능 추가
sparta-incubating/rchive-back pull request #34
Opened 2024-06-28 08:40 UTC by Mayst1232

## 개요
feat(Tag): 태그를 이용하여 게시물 검색하는 기능 추가

## 작업사항
- [ ] 태그를 이용하여 게시물 검색하는 기능 추가
 
## 관련 이슈
- [ ] close #25

2024-06-28 09:42 UTC, jiisuniui requested changes
화이팅...

2024-06-28 09:42 UTC, jiisuniui commented on src/main/java/kr/sparta/rchive/domain/post/service/EducationDataService.java
> +    }
sql로 isDeleted true false 구분해서 가져오는거랑, 현재 로직 중에 더 빠른 결과가 나오는걸 찾아보면 좋을 듯 합니다.

2024-06-28 09:42 UTC, jiisuniui commented on src/main/java/kr/sparta/rchive/domain/post/service/EducationDataTagService.java
> +                .distinct()
gpt에게 재질문 부탁드립니다.

2024-06-28 09:42 UTC, jiisuniui commented on src/main/java/kr/sparta/rchive/domain/post/service/EducationDataTagService.java
> +    }
테스트 해보시져

2024-06-28 09:42 UTC, jiisuniui commented on src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
> +    }
트랙 ID List로 받아야됩니당

2024-06-28 09:42 UTC, jiisuniui commented on src/main/java/kr/sparta/rchive/domain/user/service/TrackService.java
> +    public Track findTrackById(Long userTrackId) {
변수명 userTrackId -> trackId로 변경 부탁드립니다

2024-06-28 09:42 UTC, jiisuniui commented on src/main/java/kr/sparta/rchive/domain/user/service/TrackService.java
> +                () -> new IllegalArgumentException() // 추후 커스텀 에러로 변경할 예정
이거 주석 -> ToDo로 바꿔주세요

2024-06-28 09:42 UTC, jiisuniui commented on src/main/java/kr/sparta/rchive/domain/user/service/TrackService.java
> +    public boolean checkPermission(Long userTrackId) {
변수명 userTrackId -> trackId로 변경 부탁드립니다.

2024-06-28 09:42 UTC, jiisuniui commented on src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
> +    }
이 친구의 역할 한번만 확인해주세요
1. 하나의 track의 나의 role 확인인지
2. 내가 해당하는 모든 track의 나의 role 확인인지

2024-06-28 09:42 UTC, jiisuniui commented on src/main/java/kr/sparta/rchive/domain/user/repository/UserRepository.java
> +    Long findTrackId(String email);
class 이름 조금 명확하게 해주시면 감사하겠습니다
ex) findTrackIdByUserEmail

2024-06-28 09:42 UTC, jiisuniui commented on src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepository.java
> +    Role findByTrack_IdAndUser_Id(Long trackId, Long userId);
_ 빼주세요

2024-06-28 09:42 UTC, jiisuniui commented on src/main/java/kr/sparta/rchive/domain/post/service/EducationDataTrackService.java
> +                    EducationDataTrack edt = findByEducationDataId(educationData);
findByEducationDataId 여기서 isDeleted false 먼저 해주면 좋을 것 같습니다

2024-06-28 09:42 UTC, jiisuniui commented on src/main/java/kr/sparta/rchive/domain/post/service/EducationDataTrackService.java
> +                    EducationDataTrack edt = findByEducationDataId(educationData);
findByEducationDataId 여기서 isDeleted false 먼저 해주면 좋을 것 같습니다

2024-06-28 09:42 UTC, jiisuniui commented on src/main/java/kr/sparta/rchive/domain/post/service/EducationDataTrackService.java
> +    public List<Long> filterEducationDataIdListByTrackName(List<Long> educationDataIdList, Track userTrack) {
Track userTrack -> string trackname으로 해야될 것 같습니다.

2024-06-28 09:42 UTC, jiisuniui commented on src/main/java/kr/sparta/rchive/domain/core/service/EducationDataTagCoreService.java
> +    }
리뷰해둔 것들 변경 후 확인 @jiisuniui

2024-06-28 09:51 UTC, Mayst1232 commented on src/main/java/kr/sparta/rchive/domain/post/service/EducationDataTrackService.java
> +                    EducationDataTrack edt = findByEducationDataId(educationData);
DB에서 가져올 때 isdeleted까지 필터링하는 방식으로 변경하였습니다.

2024-06-28 09:57 UTC, Mayst1232 commented on src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
> +    }
어 이거 근데 로그인한 사람이 선택한 계정으로 검색하는거라 트랙ID가 해당 유저가 선택한 트랙 하나만 존재하지않을까요..?

2024-06-28 10:00 UTC, Mayst1232 commented on src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
> +    }
내가 현재 로그인한 계정의 role을 확인하는 로직입니다!
하나의 track에서 나의 role 확인이라고 생각해야될 것 같습니다!

2024-07-01 01:36 UTC, jiisuniui reviewed
good

2024-07-01 01:36 UTC, jiisuniui commented on src/main/java/kr/sparta/rchive/domain/post/service/EducationDataTagService.java
> +    }
이건 나중에 테스트 하면 될 듯

2024-07-01 01:38 UTC, jiisuniui commented on src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
> +    }
카톡으로 얘기 완료

2024-07-01 01:40 UTC, jiisuniui approved these changes

2024-07-01 01:43 UTC, merged